# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera.name: "iPhone"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 2000
Camera.fy: 2000
Camera.cx: 960
Camera.cy: 540

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.fps: 30.0
Camera.cols: 1920
Camera.rows: 1080

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 4000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
# Feature.mask_rectangles:
#   - [0.0, 1.0, 0.0, 0.1]
#   - [0.0, 1.0, 0.84, 1.0]
#   - [0.0, 0.2, 0.7, 1.0]
#   - [0.8, 1.0, 0.7, 1.0]
